config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :posts
  resources :homes
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :set_event, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.user = current_user
     

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Astuce créée avec succès." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Modifié !" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Supprimé !" }
      format.json { head :no_content }
    end
  end

  #######
  private
  #######

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for_flash(type)
        case type
          when 'notice' then "alert-info"
          when 'success' then "alert-success"
          when 'error' then "alert-danger"
          when 'alert' then "alert-warning"
        end
      end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">


  <p>
    <strong>Intitulé du concours:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>
  
  <p>
    <strong>Date du concours:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>Nombre de jours:</strong>
    <%= event.duration %>
  </p>

  <p>
    <strong>Prix de l'engagement en €:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>Ville:</strong>
    <%= event.location %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Organiser un concours</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Voir ce concours", @event %> |
  <%= link_to "Revenir aux concours", events_path %>
</div>

app/views/events/index.html.erb
<center><h1>Concours</h1></center>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Voir ce concours", event %>
      <%= link_to "Revenir  concours", events_path %>
    </p>
  <% end %>
</div>

<%= link_to "créer un concours", new_event_path %>

app/views/events/new.html.erb
<h1>Nouveau concours</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Revenir aux concours", events_path %>
</div>

app/views/events/show.html.erb
<%= render @event %>

<div>
  <%= button_to "Modifier ce concours", edit_event_path(@event) %> |
  <%= button_to "Revenir aux concours", events_path %>

  <%= button_to "Supprimer ce concours", @event, method: :delete %>
</div>

app/views/homes/_form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/_home.html.erb
<div id="<%= dom_id home %>">
 

</div>

app/views/homes/index.html.erb
<p>
<center><h1><strong>BIENVENUE LES CHATONS !!!</strong></h1></center>
</p>
<br>
<br>
<br>

<p>
<center><h3><strong>Retrouvez ici les trucs et astuces de nos amis à moustaches !</strong></h3></center>
</p>

<div class="d-grid gap-2">
<%= link_to "Go s'inscrire", new_user_session_path, class:"btn btn-secondary" %>

</div>

app/views/homes/show.html.erb
<%= render @home %>

<div>
  <%= link_to "Edit this home", edit_home_path(@home) %> |
  <%= link_to "Back to homes", homes_path %>

  <%= button_to "Destroy this home", @home, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type)%> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- CDN de Bootstrap -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  </head>


<!-- ma petite navbarre d'amour -->

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
          <a class="nav-link active" <%=link_to"Accueil", homes_path%></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" <%=link_to"Catlover", user_session_path%></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" <%=link_to"Astuces", posts_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%=link_to"Concours Loof", events_path%></a>
        </li>
      </ul>
      <% if user_signed_in? %>
      <%= current_user.first_name %>
      <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete %>
      <% else %>
      <%= button_to "Se connecter", new_user_session_path %>
      <% end %>
      <!-- <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary me-md-2"><%= button_to "sign_up", new_user_registration_path %></button>
        <button class="btn btn-primary"<%= button_to "sign_in", new_user_session_path %>></button>
      </div> -->

    </div>
  </div>
</nav>

  <body>
<%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Catlover:</strong>
    <%= link_to "post.user", user %>
  </p>

  <p>
    <strong>Astuce:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Commentaire:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Écris ton astuce</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Regarde cette astuce", @post %> |
  <%= link_to "Retourne aux autres astuces", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: red"><%= notice %></p>

<center><h1>Astuces</h1></center>

<!-- <ul>
<% if user_signed_in? %>
  <li><%= current_user.email %></li>
  <li><%= link_to "sign out", destroy_user_session_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Es-tu sûr(e)?"
                  } %></li>

<% else %>
<li><%= link_to "sign_in", new_user_session_path %></li>
<li><%= link_to "sign_up", new_user_registration_path %></li>
<% end %>
</ul> -->

<h2><p><%=link_to "Nouvelle astuce", new_post_path%></p></h2>


<div id="posts"><center>
  <% @posts.each do |post| %>
    <h3><%= link_to post.title, post %></h3>
    <p> Par : <%=link_to post.user.first_name, post.user %><br>
   
    <%= button_to "Modifier", edit_post_path(post) %><%= button_to "Supprimer", post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Es-tu sûr(e)?"
    } %><%= button_to "Voir cette astuce", post %>
    </p>
  <% end %>
  </center>
</div>

app/views/posts/new.html.erb
<h1>Nouvelle astuce</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Retourner aux astuces", posts_path %>
</div>

app/views/posts/show.html.erb
<!-- <%= render @post %> -->

<center><h1>Astuces n°<%= @post.id %></h1></center>

<center><h1><%= @post.title %></h2></center>

<center><h4><p><%= @post.content %></p></h4></center>
<li><p>Créé le <%= @post.created_at %></p></li>
<li><p>Créé par <%= @post.user.first_name.nil? ? @post.user.email : "#{@post.user.first_name} #{@post.user.last_name}" %></p></li>


<div><center>
  <%= button_to "Modifier cette astuce", edit_post_path(@post) %>
  <%= button_to "Supprimer cette astuce", @post, method: :delete %>
  <%= link_to "Retourner aux astuces", posts_path %>
  <%= link_to "Retourner à l'accueil", root_path %>
</div></center>

app/views/users/show.html.erb
<%= @user.first_name%>
<%= @user.last_name%>
<%= @user.age%>
<%= @user.country%>